---
title: "Final Project"
author: "Brendan Cullen"
date: "2/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

list.of.packages <- c("tidyverse", "ggplot2", "knitr", "rio", "colorblindr", "janitor", "magrittr", "ggrepel")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])] 
if (length(new.packages)) install.packages(new.packages, repos = "http://cran.us.r-project.org")
lapply(list.of.packages, library, character.only = TRUE)
```


```{r import data}
data_raw <- import("http://bchi.bigcitieshealth.org/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c6b5c30fbd8b79859797e1dc260a06064c8f3864/Current%20BCHI%20Platform%20Dataset%20(7-18)%20-%20Updated%20BCHI%20Platform%20Dataset%20-%20BCHI,%20Phase%20I%20&%20II.csv?disposition=attachment")

# wrangle data
data_filt <- data_raw %>% 
  clean_names() %>% 
  select(shortened_indicator_name, year, sex, race_ethnicity, value, place) %>% 
  filter(shortened_indicator_name %in% c("Adult Physical Activity Levels", "Teen Physical Activity Levels", "Adult Binge Drinking","Adult Obesity","Heart Disease Mortality Rate","Bike Score","Walkability","Median Household Income","Race/Ethnicity","Death Rate (Overall)")) %>% 
  mutate(value = as.numeric(value)) %>% 
  mutate_at(c("sex", "race_ethnicity", "place"), factor) %>% 
  na.omit()
```


```{r plot health outcomes by city}
# Obesity
data_filt %>% 
  filter(shortened_indicator_name == "Adult Obesity",
         place != "U.S. Total") %>% 
  spread(shortened_indicator_name, value) %>% 
  group_by(place) %>% 
  summarise(avg_obesity = mean(`Adult Obesity`, na.rm = TRUE)) %>% 
  ggplot(aes(fct_reorder(place, avg_obesity), avg_obesity)) + 
  geom_col() + 
  coord_flip()

# Heart Disease Mortality Rate
data_filt %>% 
  filter(shortened_indicator_name == "Heart Disease Mortality Rate",
         place != "U.S. Total") %>% 
  mutate(i = row_number()) %>% # add a unique index column to prevent spread from   trying to collapse duplicate rows
  spread(shortened_indicator_name, value) %>% 
  select(-i) %>% 
  group_by(place) %>% 
  summarise(avg_hdmr = mean(`Heart Disease Mortality Rate`, na.rm = TRUE)) %>% 
  ggplot(aes(fct_reorder(place, avg_hdmr), avg_hdmr)) + 
  geom_col() + 
  coord_flip()

# Adult Binge Drinking
data_filt %>% 
  filter(shortened_indicator_name == "Adult Binge Drinking",
         place != "U.S. Total") %>% 
  mutate(i = row_number()) %>% # add a unique index column to prevent spread from   trying to collapse duplicate rows
  spread(shortened_indicator_name, value) %>% 
  select(-i) %>% 
  group_by(place) %>% 
  summarise(avg_binge_drink = mean(`Adult Binge Drinking`, na.rm = TRUE)) %>% 
  ggplot(aes(fct_reorder(place, avg_binge_drink), avg_binge_drink)) + 
  geom_col() + 
  coord_flip()

# Overall Death Rate
data_filt %>% 
  filter(shortened_indicator_name == "Death Rate (Overall)",
         place != "U.S. Total") %>% 
  mutate(i = row_number()) %>% # add a unique index column to prevent spread from   trying to collapse duplicate rows
  spread(shortened_indicator_name, value) %>% 
  select(-i) %>% 
  group_by(place) %>% 
  summarise(avg_death_rate = mean(`Death Rate (Overall)`, na.rm = TRUE)) %>% 
  ggplot(aes(fct_reorder(place, avg_death_rate), avg_death_rate)) + 
  geom_col() + 
  coord_flip()
```

## replace bars with dots and add se bars. figure out units for x axes. add title. 

```{r Scatter plots}
# create summary data set
summary <- data_filt %>%
  filter(shortened_indicator_name %in% c("Adult Obesity", "Heart Disease Mortality Rate"),
         place != "U.S. Total") %>%
  mutate(i = row_number()) %>%
  spread(shortened_indicator_name, value) %>%
  group_by(place) %>%
  mutate(avg_obesity =  mean(`Adult Obesity`, na.rm = TRUE),
         avg_hdmr = mean(`Heart Disease Mortality Rate`, na.rm = TRUE))

# plot obesity by heart disease mortality rate 
data_filt %>% 
  filter(shortened_indicator_name %in% c("Heart Disease Mortality Rate", "Adult Obesity"),
         place != "U.S. Total") %>% 
  mutate(i = row_number()) %>%
  spread(shortened_indicator_name, value) %>% 
  group_by(place) %>% 
  summarise(avg_hdmr = mean(`Heart Disease Mortality Rate`, na.rm = TRUE),
            avg_obesity = mean(`Adult Obesity`, na.rm = TRUE)) %>% 
  ggplot(aes(avg_obesity, avg_hdmr)) + 
  geom_point() +
  geom_text_repel(aes(label = place)) + 
  geom_smooth(method = "lm")
```

## Note: data missing for Cleveland, OH and Charlotte, NC. 
## ideas: label and use color to highlight top 3 most/least obese cities

```{r Demographic variables}

```

